AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with Intelligent-Tiering (excluding Glacier) and encryption.

Parameters:
  BucketName:
    Description: "Enter the name of the S3 bucket to create"
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: "IntelligentTieringRule"
            Status: "Enabled"
            Transitions:
              - StorageClass: "INTELLIGENT_TIERING"
                TransitionInDays: 30
          - Id: "DeleteExpiredMarkersAndMultipartUploads"
            Status: "Enabled"
            ExpiredObjectDeleteMarker: true
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: "Created S3 Bucket Name"
    Value: !Ref BucketName
